google_oauth2:
    client_id: 292...rkl.apps.googleusercontent.com
    client_secret: 7i...ng
    callback_url: https://docs.example.com/auth/google/callback
allow_insecure_dev_login: true
allowed_emails:
    - developer1@example.com
    - developer2@example.com
session_secret: topsecretstringhere
overwatch_hub:
    api_url: http://127.0.0.1:8090
    client_token: secret_client_token
port: 3000
